/**
 * Shared test fixtures for integration tests.
 * Each test gets an isolated temp directory.
 */
import fs from "fs";
import path from "path";
import os from "os";

export interface Fixture {
    tmpDir: string;
    swarmDir: string;
    configDir: string;
    cleanup(): void;
}

/**
 * Minimal swarm-manifest template for tests.
 */
const SWARM_MANIFEST_TEMPLATE = `# Swarm Manifest
> Generated by /swarm at $TIMESTAMP

## Mission
$MISSION

## Mode
Supervision: supervised
Auto-merge: false

## Agents

| ID | Role | Model | Scope | Status | Phase |
|----|------|-------|-------|--------|-------|

## File Claims

| File | Claimed By | Status |
|------|-----------|--------|

## Phase Gates
- [ ] Phase 1 complete
- [ ] Phase 2 complete
- [ ] Phase 3 complete

## Handoff Notes

## Branches

| Agent | Branch | Status |
|-------|--------|--------|

## Issues

| Severity | File/Area | Description | Reported By |
|----------|-----------|-------------|-------------|
`;

/**
 * Create an isolated temp workspace for a test.
 * Automatically creates .swarm/ subdirectory.
 */
export function createFixture(prefix = "ac-integration-"): Fixture {
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
    const swarmDir = path.join(tmpDir, ".swarm");
    fs.mkdirSync(swarmDir, { recursive: true });

    // Provision config directory with required templates
    const configDir = path.join(tmpDir, ".config");
    const templatesDir = path.join(configDir, "templates");
    fs.mkdirSync(templatesDir, { recursive: true });

    // Write minimal swarm-manifest template
    fs.writeFileSync(path.join(templatesDir, "swarm-manifest.md"), SWARM_MANIFEST_TEMPLATE);

    return {
        tmpDir,
        swarmDir,
        configDir,
        cleanup() {
            try {
                fs.rmSync(tmpDir, { recursive: true, force: true });
            } catch {
                // Windows may have lingering file locks — best effort
            }
        }
    };
}

/**
 * Read a file from the fixture directory.
 * Returns null if file doesn't exist.
 */
export function readFixtureFile(tmpDir: string, relativePath: string): string | null {
    const fullPath = path.join(tmpDir, relativePath);
    return fs.existsSync(fullPath) ? fs.readFileSync(fullPath, "utf8") : null;
}

/**
 * Check if a file exists in the fixture directory.
 */
export function fixtureFileExists(tmpDir: string, relativePath: string): boolean {
    return fs.existsSync(path.join(tmpDir, relativePath));
}
